{"timestamp":"2025-09-18T19:29:31.764230","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-18T19:29:31.766767","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/test.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-18T19:29:32.031232","level":"info","event":"Executing: \n            USE db_alpha_vantage;\n            SELECT * FROM state_index_silver;\n        ","logger":"airflow.task.operators.airflow.providers.microsoft.mssql.operators.mssql.MsSqlOperator"}
{"timestamp":"2025-09-18T19:29:32.039443","level":"warning","event":"Using Connection.get_connection_from_secrets from `airflow.models` is deprecated.Please use `get` on Connection from sdk(`airflow.sdk.Connection`) instead","category":"DeprecationWarning","filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py","lineno":471,"logger":"py.warnings"}
{"timestamp":"2025-09-18T19:29:32.119543","level":"info","event":"Connection Retrieved 'testConnection'","logger":"airflow.hooks.base"}
{"timestamp":"2025-09-18T19:29:32.193673","level":"info","event":"Connection Retrieved 'testConnection'","logger":"airflow.hooks.base"}
{"timestamp":"2025-09-18T19:29:32.428813","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OperationalError","exc_value":"(18456, b\"Login failed for user 'adminalpha'.DB-Lib error message 20018, severity 14:\\nGeneral SQL Server error: Check messages from the SQL Server\\nDB-Lib error message 20002, severity 9:\\nAdaptive Server connection failed (server-alpha-vantage.database.windows.net)\\nDB-Lib error message 20002, severity 9:\\nAdaptive Server connection failed (server-alpha-vantage.database.windows.net)\\n\")","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1215,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py","lineno":312,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py","lineno":763,"name":"run"},{"filename":"/usr/local/lib/python3.12/contextlib.py","lineno":137,"name":"__enter__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py","lineno":870,"name":"_create_autocommit_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/microsoft/mssql/hooks/mssql.py","lineno":98,"name":"get_conn"},{"filename":"/opt/airflow/src/pymssql/_pymssql.pyx","lineno":659,"name":"pymssql._pymssql.connect"}],"is_group":false,"exceptions":[]},{"exc_type":"MSSQLDatabaseException","exc_value":"(18456, b\"Login failed for user 'adminalpha'.DB-Lib error message 20018, severity 14:\\nGeneral SQL Server error: Check messages from the SQL Server\\nDB-Lib error message 20002, severity 9:\\nAdaptive Server connection failed (server-alpha-vantage.database.windows.net)\\nDB-Lib error message 20002, severity 9:\\nAdaptive Server connection failed (server-alpha-vantage.database.windows.net)\\n\")","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/opt/airflow/src/pymssql/_pymssql.pyx","lineno":650,"name":"pymssql._pymssql.connect"},{"filename":"/opt/airflow/src/pymssql/_mssql.pyx","lineno":2158,"name":"pymssql._mssql.connect"},{"filename":"/opt/airflow/src/pymssql/_mssql.pyx","lineno":712,"name":"pymssql._mssql.MSSQLConnection.__init__"},{"filename":"/opt/airflow/src/pymssql/_mssql.pyx","lineno":1884,"name":"pymssql._mssql.maybe_raise_MSSQLDatabaseException"},{"filename":"/opt/airflow/src/pymssql/_mssql.pyx","lineno":1901,"name":"pymssql._mssql.raise_MSSQLDatabaseException"}],"is_group":false,"exceptions":[]}]}
